### ISSUE TITLE
Please, add some documentation/mentioning of bo/bs options

### ISSUE THREAD

**Issue by Codereamp** [SubtitleEdit/subtitleedit#8305]
I forgot that my MSI notebook had a NVIDIA MX330 capable of CUDA, but it produced "out of memory" errors most of the time (according to the settings it has 2GB dedicated memory). Just by chance I saw the [comment](https://github.com/SubtitleEdit/subtitleedit/issues/7600#issuecomment-1798404638) about bo/bs options. In my case enabling both (bo only didn't help) worked and ratio 0.7 audio secs/s changed to 4 audio secs/s (medium model)

I suspect that much more users might use CUDA on a consumer-level notebooks with NVIDIA, but it looks like both options not outputted in help. Also a short phrase about the options somewhere on the frontpage/release might help to encourage the usage 

Thanks

**Comment by Codereamp** [comment]
Correction, I found the options in the help output so 

```
  --best_of BEST_OF, -bo BEST_OF
                        number of candidates when sampling with non-zero
                        temperature (default: 5)
  --beam_size BEAM_SIZE, -bs BEAM_SIZE
                        number of beams in beam search, only applicable when
                        temperature is zero (default: 5)
```
so it's more not about presence of the options in the docs, but rather knowing what to do.

And if interpreting my troubles with CUDA on NVIDIA MX330/2GB, that meant that `-bo=5 -bs=5` isn't suitable for such a configuration, but `-bo=1 -bs=1` worked for me.

Also as the search shows , these options are specific to whisper in general, not SYSTRAN faster-whisper or whisper-faster. 

Probably the issue can be closed unless the author would like a append something at the frontpage for non-advanced users :)

Thanks

**Comment by Codereamp** [comment]
Final admission, I probably should have post it at Purfview/whisper-standalone-win page, so closing...
