### ISSUE TITLE
No Text found error

### ISSUE THREAD

**Issue by RED03410** [SubtitleEdit/subtitleedit#9445]
After changing the system today
Error using Audio to Text (Whisper).
The changed system used CPU 5800X3d and GPU GTX5080.

Attached is Whisper_log.txt.

-----------------------------------------------------------------------------
Date: 03/09/2025 09:13:00
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit
Message: C:\Users\RED\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language en --model "small" --standard --beep_off "C:\Users\RED\AppData\Local\Temp\b13e2487-4989-4561-b7c6-36b3ade652db.wav"

-----------------------------------------------------------------------------
Date: 03/09/2025 09:13:11
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper-XXL) with : C:\Users\RED\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language en --model "small" --standard --beep_off "C:\Users\RED\AppData\Local\Temp\b13e2487-4989-4561-b7c6-36b3ade652db.wav"
Standalone Faster-Whisper-XXL r245.1 running on: CUDA
Starting sequential inference to transcribe: C:\Users\RED\AppData\Local\Temp\b13e2487-4989-4561-b7c6-36b3ade652db.wav
Traceback (most recent call last):

[PYI-6400:ERROR] Failed to execute script '__main__' due to unhandled exception!

RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED

File "faster_whisper\transcribe.py", line 1719, in encode

File "faster_whisper\transcribe.py", line 1471, in generate_segments

File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps

File "D:\whisper-fast-XXL\__main__.py", line 1943, in cli

File "D:\whisper-fast-XXL\__main__.py", line 2071, in <module>
Calling whisper Purfview's Faster-Whisper-XXL done in 00:00:08.3415339
Loading result from STDOUT

**Comment by Purfview** [comment]
Use `--compute_type float16`

**Comment by RED03410** [comment]
This problem has been solved in the way you told me.

Thank you very much.
